name = "durable-objects"
main = "durable-objects.ts"
compatibility_date = "2023-12-01"
first_party_worker = true

[[durable_objects.bindings]]
name = "EchoDo"
class_name = "EchoDo"

[[migrations]]
tag = "v1"
new_classes = ["EchoDo"]
